//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    
    public partial class IdSuperDigitoGetResultado_Result1
    {
        public int IdHistorial { get; set; }
        public int IdSuperDigito { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> Resultado { get; set; }
    }
}
