//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExamenSICOSSEntities : DbContext
    {
        public ExamenSICOSSEntities()
            : base("name=ExamenSICOSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Historial> Historials { get; set; }
        public virtual DbSet<SuperDigito> SuperDigitoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int AddHistorial(Nullable<int> idUsuario, Nullable<int> idSuperDigito)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idSuperDigitoParameter = idSuperDigito.HasValue ?
                new ObjectParameter("IdSuperDigito", idSuperDigito) :
                new ObjectParameter("IdSuperDigito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddHistorial", idUsuarioParameter, idSuperDigitoParameter);
        }
    
        public virtual ObjectResult<GetUsername_Result> GetUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsername_Result>("GetUsername", usernameParameter);
        }
    
        public virtual ObjectResult<IdUsuarioGetHistorial_Result> IdUsuarioGetHistorial(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IdUsuarioGetHistorial_Result>("IdUsuarioGetHistorial", idUsuarioParameter);
        }
    
        public virtual int AddSuperDigito(ObjectParameter idSuperDigito, Nullable<int> numero, Nullable<int> resultado)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var resultadoParameter = resultado.HasValue ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSuperDigito", idSuperDigito, numeroParameter, resultadoParameter);
        }
    
        public virtual int AddUsuario(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUsuario", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<IdSuperDigitoGetResultado_Result1> IdSuperDigitoGetResultado(Nullable<int> idSuperDigito)
        {
            var idSuperDigitoParameter = idSuperDigito.HasValue ?
                new ObjectParameter("IdSuperDigito", idSuperDigito) :
                new ObjectParameter("IdSuperDigito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IdSuperDigitoGetResultado_Result1>("IdSuperDigitoGetResultado", idSuperDigitoParameter);
        }
    
        public virtual ObjectResult<IdUsuarioGetNumero_Result> IdUsuarioGetNumero(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IdUsuarioGetNumero_Result>("IdUsuarioGetNumero", idUsuarioParameter);
        }
    
        public virtual int UpdateFecha(Nullable<int> numero, Nullable<int> idSuperdigito)
        {
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(int));
    
            var idSuperdigitoParameter = idSuperdigito.HasValue ?
                new ObjectParameter("IdSuperdigito", idSuperdigito) :
                new ObjectParameter("IdSuperdigito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateFecha", numeroParameter, idSuperdigitoParameter);
        }
    
        public virtual int DeleteHistorialIdUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteHistorialIdUsuario", idUsuarioParameter);
        }
    }
}
