//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperDigito
    {
        public SuperDigito()
        {
            this.Historials = new HashSet<Historial>();
        }
    
        public int IdSuperDigito { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> Resultado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual ICollection<Historial> Historials { get; set; }
    }
}
